### ISSUE TITLE
JSON lib can't handle BigInt

### ISSUE THREAD

**Issue by mislam** [pokt-network/pocket-js#38]
The built-in `JSON.stringify` doesn't know how to serialize a `BigInt`. I'd recommend looking into [json-bigint](https://www.npmjs.com/package/json-bigint) or something similar.

https://github.com/pokt-foundation/pocket-js-slim/blob/10efcca022682c806bc650fe0ef0c92a4da2edd9/packages/provider/src/isomorphic-provider.ts#L93

Also, when I called the `getBalance` method, it's returning `number` instead of `bigint`.

https://github.com/pokt-foundation/pocket-js-slim/blob/10efcca022682c806bc650fe0ef0c92a4da2edd9/packages/provider/src/isomorphic-provider.ts#L127-L128

Typecasting with `as` is not working. But doing `return BigInt(balance)` works. That means you assume balance returning from JSON is a `number`, and not `bigint`. I hope solving the first problem would suffice and won't require a typecasting.

**Update (April 19)**: After trying out `json-bigint`, I noticed it doesn't treat small numbers as `bigint` although they are declared as bigint. It takes bigint as bigint only when the number is big enough to go beyond the maximum range of `number` type. So, I still feel this is a bit problemetic to use this library over the standard JSON lib. For now, I am just typecasting the `bigint` to `number` as that can safely handle 9 quadrillion uPOKT (=9 billion POKT). That's enought for me for now. Although this is not the best solution for long run. And I'm also not sure how this max range would vary on a lower-end machine like a 32-bit computer or an old smartphone with lower-end cpu.

**Comment by Evalir** [comment]
Hey sir! I've merged #47 which should fix this in the interim. Ideally, we'd unmarshal directly into a `bigint` value, but this might require a core change as they get sent as a number through JSON (and probably as a string once it's too big to handle).
