### ISSUE TITLE
Provider: more specific on RPC errors

### ISSUE THREAD

**Issue by crisog** [pokt-network/pocket-js#65]
If you attempt to query a node, and it is not found (no validator found error from core) - it throws a generic RPC error. It should be more specific.

**Comment by nodiesBlade** [comment]
Whenever RPC fails for me, all i get is
```
et error = new AbortError('The user aborted a request.');
                                    ^
AbortError: The user aborted a request.
```
Is this intended behavior? It's not very specific at all. Is my connection timing out / how can we control the timeout?
