### ISSUE TITLE
[BUG REPORT] JSONRPCProvider returning abort errors

### ISSUE THREAD

**Issue by nodiesBlade** [pokt-network/pocket-js#74]
**Describe the bug**
Whenever sending a request to the RPC provider, I get this error:

```
Users/iuas/WebstormProjects/untitled/node_modules/undici/lib/fetch/webidl.js:19
  throw new TypeError(`${message.header}: ${message.message}`)
        ^
TypeError: AbortSignal: Expected [object AbortSignal] to be an instance of AbortSignal.
```

This occurs regardless of my pokt RPC url (localhost, or portal rpc endpoint). I've tried simple query methods such as provider.getBalance (from the readme example) alongside submit tx methods and none of them works and returns the above error.

I am currently on 1.2.0 of pocketjs slim according to my package-lock json file.

OS: M1 Mac, Node 16

**Comment by nodiesBlade** [comment]
I've swapped over to IsomorphicProvider and things seem to be working. Not sure what the cause of this is? Regardless, why would one use JsonRPCProvider when IsomorphicProvider is avaliable?

**Comment by nodiesBlade** [comment]
Update: Perhaps, it's due to my total crap internet since I'm traveling. I see that there is a 1s timeout before it aborts. I didn't see a way to configure this timeout

**Comment by crisog** [comment]
> I've swapped over to IsomorphicProvider and things seem to be working. Not sure what the cause of this is? Regardless, why would one use JsonRPCProvider when IsomorphicProvider is avaliable?

IsomorphicProvider is better suited when using it on a browser, and regular provider when you are doing server side work. The dependencies used in the regular provider are not suited for browser.



> Update: Perhaps, it's due to my total crap internet since I'm traveling. I see that there is a 1s timeout before it aborts. I didn't see a way to configure this timeout

You can configure the timeout per call,
```
const apps = await simpleProvider.getApps({
  page: 1,
  perPage: 500,
  // customizable timeout
  timeout: 5000
})
```

**Comment by nodiesBlade** [comment]
@crisog Thanks for the provider context.

I see getApps has timeout, but how about `getBalance`, `transactionBuilder` objects, etc? Those methods are lacking timeout as part of the function signature. It would be nice to have a configurable timeout on the provider level and on the call level.

**Comment by crisog** [comment]
> @crisog Thanks for the provider context.
> 
> I see getApps has timeout, but how about `getBalance`, `transactionBuilder` objects, etc? Those methods are lacking timeout as part of the function signature. It would be nice to have a configurable timeout on the provider level and on the call level.

Agreed. Can you open an issue for this specifically?

**Comment by nodiesBlade** [comment]
@crisog For sure, I'll close this one, reference it, and create a new one.
