### ISSUE TITLE
[BUG REPORT] JSONRPCProvider  received an instance of AbortSignal

### ISSUE THREAD

**Issue by AlburIvan** [pokt-network/pocket-js#85]
**Describe the bug**

Currently trying to implement a simple RPC call to `getBalance` (and others), but I get the error below whenever I try to invoke said functionalities.

`TypeError [ERR_INVALID_ARG_TYPE]: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal`

It's similar to #74 and #75, but those didn't have a solution for the problem itself

**To Reproduce**
```ts
import { JsonRpcProvider } from '@pokt-foundation/pocketjs-provider'

const rpcUrl = 'https://mainnet.gateway.pokt.network/v1/lb/<PORTAL_ID>'

const dispatchers = [
  'https://node001.<REDACTED>.org',
  'https://node002.<REDACTED>.org'
]

const provider = new JsonRpcProvider({
  rpcUrl,
  dispatchers,
})

const balance = await simpleProvider.getBalance(
  'a8b23ebca16cde7f0a02b59db0eff9bea2300d4e',
);
```

**Expected behavior**
Get balance (or any other action) from said address

**Screenshots**
![image](https://user-images.githubusercontent.com/10523232/221955497-33a38907-c82a-405b-8056-b1ea74fec142.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Environment: Node
 - Version: tested in `v16.9.0` and `v18.14.2`
 - Library Version: `^2.1.0`

**Additional context**
Am I missing something here?

**Comment by msmania** [comment]
Closing this issue as no repro on my end.  If you're still having the same issue with the latest version, please feel free to reopen this.

Please note that the endpoint under mainnet.gateway.pokt.network is no longer valid.  You can get a POKT endpoint through a gateway (Nodies or Grove).  See more details [here](https://docs.pokt.network/developers/use-a-gateway).
